### ISSUE TITLE
Type piracy on `hash` breaks `hash(())`

### ISSUE THREAD

**Issue by mofeing** [ArrogantGao/TreeWidthSolver.jl#16]
The following code is type-piracy, and breaks the integration I have between Tenet.jl and Reactant.jl. In particular, I'm using OMEinsum.jl which loads OMEinsumContractionOrders.jl which loads TreeWidthSolver.jl. And Reactant.jl at some points needs to call `hash(())`, which is overloaded here:

https://github.com/ArrogantGao/TreeWidthSolver.jl/blob/572bbd13a1c1c9a25a6581e21b499596f437d4be/src/bitbasis.jl#L13-L19

Would you mind changing this and not type-pirating `Base.hash`? In particular, the type-piracy appears because if `N=0`, then `NTuple{0, ULonLongInt} == Tuple{}` when doing multiple dispatch.

# MWE

```julia
julia> hash(())
0x77cfa1eef01bca90

julia> using TreeWidthSolver

julia> hash(())
ERROR: BoundsError: attempt to access Tuple{} at index [1]
Stacktrace:
 [1] getindex(t::Tuple, i::Int64)
   @ Base ./tuple.jl:31
 [2] hash(bits_tuple::Tuple{})
   @ TreeWidthSolver ~/.julia/packages/TreeWidthSolver/rHpdc/src/bitbasis.jl:14
 [3] top-level scope
   @ REPL[5]:1
```

**Comment by ArrogantGao** [comment]
Sorry for my mistake, thank you very much for pointing that out and fixing it.
The PR has already been merged.

**Comment by mofeing** [comment]
Thanks for your fast response!
