### ISSUE TITLE
Documentations

### ISSUE THREAD

**Issue by ArrogantGao** [ArrogantGao/TreeWidthSolver.jl#6]

**Comment by GiggleLiu** [comment]
Add a table that shows the performance.

**Comment by GiggleLiu** [comment]
Add a link to OMEinsumContractionOrders.jl in README.

**Comment by GiggleLiu** [comment]
https://github.com/openjournals/joss-reviews/issues/7098#issuecomment-2281995862

**Comment by ArrogantGao** [comment]
documentation added, see https://arrogantgao.github.io/TreeWidthSolver.jl/stable/
